apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqlserver
  labels:
    app: mysqlapp
spec:
  selector:
    matchLabels:
      app: mysqlapp
  template:
    metadata:
      labels:
        app: mysqlapp
    spec:
      containers:
      - name: mysql-db
        image: mysql:8.0.31
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: wenomaichainsama
        - name: MYSQL_DATABASE
          value: myDB
        - name: MYSQL_USER
          value: dbUser
        - name: MYSQL_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: mysqlcontainer
        args: ["--default_authentication_plugin=mysql_native_password"]
        volumeMounts:
        - name: mysql-volume
          mountPath: /var/lib/mysql/
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-pvc
